### ISSUE TITLE
Cannot read property 'formats' of undefined

### ISSUE THREAD

**Issue by narcolepticinsomniac** [tophf/yt-hover#1]
[Example](https://old.reddit.com/r/videos/comments/g726qv/mary_neely_belle_from_beauty_and_the_beast_1991/)

Wish I'd had greasyfork notifications on, so I would've known you forked this before dicking around with it for days. FYTE with schomery's version just had too many issues, so I borrowed your parser and tried to hook up a script to execute inside iframes. 

I'm also running into way more gvideo failures than I expected, having used invidio redirects. Aren't they using the same API? Why are they able to pull gvideo links for videos where this script falls back to a YT player?

Example:

https://www.youtube.com/embed/UiYpQaQqhkk

https://invidio.us/embed/UiYpQaQqhkk?raw=1

Too bad invidio has been become so slow and unreliable, they're basically unusable.

**Comment by tophf** [comment]
I'm using `https://www.youtube.com/get_video_info` service and it tells me that this video is playable only on youtube. I've tried spoofing HTTP request headers (Origin, Referer, Access-Control-Allow-Origin) for the direct video links but I couldn't hack it and the response was always 403 (forbidden).

Now the frame player will be used in such cases right away.

**Comment by narcolepticinsomniac** [comment]
Hmm. [Local YT Downloader](https://greasyfork.org/en/scripts/369400-local-youtube-downloader) seems to use the `&el=detailpage` parameter with great success. Maybe there's something to that.

**Comment by tophf** [comment]
Changing just that doesn't help, same 403 response when playing the actual video stream.

**Comment by narcolepticinsomniac** [comment]
Damn. I can't even copy the right answers correctly. =) Well, the fallback's kicking in now, so I guess this issue's closed.

**Comment by tophf** [comment]
Youtube apparently is changing the way they serve the videos because earlier today I used the native player a lot and now the same videos don't play directly anymore.

**Comment by narcolepticinsomniac** [comment]
Yeah, when I used FYTE previously, it seemed to have a much higher success rate. Part of the problem with invidious appears to be that YT doesn't cooperate like it used to. It's like they regret offering the API, and they're probably obligated to maintain it to a certain extent at this point, so they self sabotage at every turn.

**Comment by tophf** [comment]
Today, it works on those videos...
