### ISSUE TITLE
`This extension violates the Chrome Web Store policy` in Chrome Extensions list

### ISSUE THREAD

**Issue by darkred** [tophf/yt-hover#2]
Greetings @tophf 

I have your extension sideloaded in Chrome browser a long time now (thanks for your work!).

Recently, after upgrading Chrome to v90
I see the following message `This extension violates the Chrome Web Store policy` in `chrome://extensions/`:
![2021-04-17_162235](https://user-images.githubusercontent.com/723651/115114669-2c7af380-9f99-11eb-936a-5f83e45e44ba.jpg)

I even removed the extension and sideloaded it again.
After restarting Chrome, initially there was no message, but some time the message appeared again.

The extension is sideloaded of course, and not available in CWS, I just wanted to mention it to you anyway.

**Comment by tophf** [comment]
This extension is not in the web store so it doesn't violate anything. The only thing that's left of the original extension is the id so I'll unbind it.

**Comment by tophf** [comment]
Done: 96936f81.

The settings will be lost though.

**Comment by darkred** [comment]
Thank you for your response.
